{% set version = "2016.16.0.3.3.210" %}

package:
  name: mkl-nonfree
  version: {{ version }}

source:
  fn: parallel_studio_xe_2016_update3.tgz
  url: http://registrationcenter-download.intel.com/akdlm/irc_nas/9061/parallel_studio_xe_2016_update3.tgz
  sha256: aa7c6f1a6603fae07c2b01409c12de0811aa5947eaa71dfb1fe9898076c2773e

build:
  number: 0
  skip: true  # [not linux]

about:
  home: http://software.intel.com/en-us/articles/non-commercial-software-download/
  license: custom
  summary: Intel Math Kernel Library (Intel® MKL)

extra:
  recipe-maintainers:
  - 183amir
